- pages/about.js
- pages/index.js
I did it right based on the tutorial, but did I do my PR right?
> adding about page and next/link

- comps/Header.js
- comps/MyLayout.js
- pages/about.js
- pages/index.js
can you explain the {props.children} under MyLayout.js? 
What are props again and how are they passed down?
> adding components to the site

- pages/about.js
- pages/index.js
- pages/post.js
I assume since post.js is already using a fat arrow function but told me to write it with the return statement if you declare another const inside the function you have to then use the return() statement vs. removing it as I did for the other pages?
> fat arrows and dynamic pages

- package-lock.json
- package.json
- pages/index.js
- pages/p/[id].js
I have a lot of questions around the getInitialProps ... function? On both the index.js and [id].js but I think more particularly on the [id].js. calling the argument (context). 
Is that from the API? 
Why didn't I use it on the Index.js file?
I assume getInitialProps is how I can then use Props in the const Post and const Index above, but how do I know there is a (props.show.name) or (props.show.summary). Is that stuff usually highlighted in the API documentation, but was skipped in the lesson since its more about Next.js than it is about API calls?
I just feel a little out of sync (see what I did there) with this particular part of the lesson.
> get initial props and dynamic routing

- components/AboutNew.js
- components/Blog.js
- components/Brews.js
- components/Carousel.js
- components/Events.js
- components/MyLayout.js
- components/TapList.js
Not a ton of time on my lunch break, but I think I have the gist of it working. Now I just need to make the slides bigger to verify its working. Ill also still need to figure out the strategy for the content, so I make sure to pull it incorrectly.
> figured out the styling for the carousel, 

- components/AboutNew.js
- components/Blog.js
- components/Brews.js
- components/Carousel.js
- components/Events.js
- components/Header.js
- components/MyLayout.js
- components/TapList.js
- pages/index.js
So I added each different section as a component and imported them to the carousel, but I can't seem to wrap my head around the structure. 
Header.js is currently pulled into layout.js, which is imported to index.js, but I think it should be pulled out and carousel.js should imported into Layout.js? Then in index.js I would import header and layout separately? I'm thinking this because in my head header.js is now going to be that side rail navigation (hamburger, title, social, location), then carousel.js would start the actual content.
Am I on the right track, or how would you handle it? 
Also not sure how to pull in the navigation correctly, I tried on the about link in the header.js component but it gets a 404 error, I'm assuming because it's not a page? but then how do you link to a …
> carousel and components

- pages/matts-page.js
Just a proof of concept with the "sticky" left-side nav bar and horizontal scroll with in-page link/link targets (technically fragment identifier links).
> Matt's Page

- components/AboutNew.js
- components/Blog.js
- components/Carousel.js
- components/Header.js
- components/MyLayout.js
- pages/index.js
Reverts potpiedigital/cognitionbrewingcompany.com#9
> Revert "Styling components and navigation"

- components/About.js
- components/Carousel.js
- components/Hamburger.js
- components/Hero.js
- components/Nav.js
- components/Section.js
Okay, adding in the background image for the hero section. Just using unsplash random for the time being. Can you pull in WP API calls into CSS? I've literally no clue what an API call returns, but I'm going to assume something like this could work?
I'm sure you have a better idea for the hamburger navigation, but for the time being I'm happy this is working ... we can call this plan B if you want. It's an absolute crap ton of CSS, so probably not the most useful on load. Should I make it it's own component? Do you have a suggestion on something else I should try and implement? I did briefly look into React Spring but it looked like a little more than I can handle, at least for tonight. It would be cool to walk through it though ... maybe later this week or weekend. This looks promising, …
> Trying some shhiii ... css!

- components/About.js
- components/Section.js
adding in CSS grid for the first time. I think I need some help and guidance to make this sustainable. It currently only looks "okay" and somewhat close to mock at 1440x1024. 
I've never done CSS grid, so I feel like I should try and set it here and use it throughout. Any thoughts and helpful hints?
> adding grid and content

- components/About.js
- components/Section.js
Reverts potpiedigital/cognitionbrewingcompany.com#17
> Revert "adding grid and content"

- components/About.js
- components/Section.js
- pages/index.js
about content added, need to adjust the grid
> Adding content

- components/About.js
- components/Carousel.js
- components/Section.js
So I tried to make individual sections wider, but I'm either doing something wrong or what I'm doing is implemented right. Can you take a look and let me know?
It seems no matter what I do, I can't get the sections to go wider. Thought I could override the individual section styling with bigStyle, but it doesn't seem to be working right ... even though the code does seem to come through in the inspector.
> Making wide sections

- components/About.js
- components/Carousel.js
- pages/index.js
Updating styling to the about section and it's closer on the smaller screen but I think there is an issue with my grid rows and need to look into it a bit better.
> about section style updates

- components/About.js
- components/Carousel.js
- components/Hero.js
adding remaining content and initial styles to hero section, one quick update to about section hr tag. Didn't have any more time on my lunch break.
> hero additions.

- components/Hero.js
finished with hero updates. I may need to update some font sizes, but I don't have my mock on this work computer, so I'll come back to that later.
> More hero updates

- components/TapList.js
initial content for the tap list section and some initial thoughts on the grid and flex-box layout.
> updating the grid and adding initial dummy content for tap list page

- components/About.js
- components/Carousel.js
- components/Hero.js
- components/Listing-item.js
- components/Nav.js
- components/TapList.js
- pages/index.js
Soooo, not really a bunch of tap list tweaks. I ended up doing SOME tap list tweaks, but I think the majority of my edits were to global styles in an attempt to make things uniform and ideally (fingers crossed) easier to breakdown when its time to go mobile.
No major issues for my side, but let me know if you see anything off.
> Tap list tweaks

- components/Carousel.js
- components/Listing-item.js
- components/On-deck.js
- components/On-tap.js
- components/TapList.js
- components/barrel-offerings.js
adding in the on deck selection and adjusting the layout for other tap lists, and making each list its own commponent.
> tap list adds. 

- components/Blog.js
- components/Carousel.js
- components/Events.js
adding in the styling for event page big text, and updating some styles on blog post
@mysterycommand any thoughts on how to bring the image on the events.js page up, so the right corner isn't getting cut off? I thought z-index would work, but it doesn't seem to be. Also, I didn't notice any overflow hidden on the container, so not sure what's going on.
> blog and event section tweaks

- components/About.js
- components/Big-text.js
- components/Blog.js
- components/Carousel.js
- components/Nav.js
- components/On-deck.js
- components/Section.js
- components/TapList.js
- pages/index.js
@mysterycommand I'm having an issue with content overflowing. You get a bottom scroll, which on this site is unwanted. 
If I put (overflow: hidden;) on sections.js everything looks fine EXCEPT the image on blog.js, it gets cut off on the left corner where it sticks over the next section. Any chance you can look into this and see where the content is overflowing?  I tried to see, but I'm not seeing anything stand out. 
Maybe its the grid? That was my last idea but I'm not sure.
> issue with content off screen

- components/About.js
- components/Blog.js
- components/Carousel.js
- components/Events.js
- components/On-deck.js
- components/On-tap.js
- components/TapList.js
- components/barrel-offerings.js
adjusting the grid and removing the overflow content. yay
@mysterycommand review if you have time, but I fixed the issue. So Im pretty happy
> fixed the grid and the issue with overflow content. 

- components/About.js
- components/Blog.js
- components/Brews.js
- components/Carousel.js
- components/Header.js
- components/On-tap.js
- components/TapList.js
- components/barrel-offerings.js
- components/forage.js
- pages/index.js
Still have some issues with pulling in className as a prop and using it to help set the grid. I have some issues with overflow again, but I think the big issue will be solved if I can get this grid and className thing to work. 
@mysterycommand can you see what I am doing wrong. I am pulling forage.js into brew.js. I've passed className as a prop to forage and then set it in brew.js. I can see the className in the inspector but no matter what I do the styling doesn't seem to want to work.
> Brew section
